# Generated by Django 4.2.4 on 2023-08-10 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlapp', '0002_alter_diabetic_age_alter_diabetic_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diabetic',
            name='Height',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='diabetic',
            name='MentHlth',
            field=models.IntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20'), (21, '21'), (22, '22'), (23, '23'), (24, '24'), (25, '25'), (26, '26'), (27, '27'), (28, '28'), (29, '29'), (30, '30')], null=True),
        ),
        migrations.AlterField(
            model_name='diabetic',
            name='PhysHlth',
            field=models.IntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20'), (21, '21'), (22, '22'), (23, '23'), (24, '24'), (25, '25'), (26, '26'), (27, '27'), (28, '28'), (29, '29'), (30, '30')], null=True),
        ),
        migrations.AlterField(
            model_name='diabetic',
            name='Weight',
            field=models.FloatField(),
        ),
    ]
